pipeline{

    agent any
    stages{
        stage('build'){
            steps{
                sh "cd java/mi-proyecto && mvn clean install"
               

            }
        }
        stage('Test'){
            steps{ 
           sh "cd java/mi-proyecto && mvn test"
        
        }
        }

        stage('Deploy'){
            steps{
            echo "simulando un despliegue simulado"
        }
        }

    }

    post{
        always{
            echo "Siempre se ewjecuta"

        }
        success{
              echo "exito"
        }

        failure{
              echo "fracazo"
        }
    }


}