pipeline{

    agent any
    stages{
        stage('build'){
            steps{
                sh "cd java/mi-proyecto"
                sh "ls"
                echo "este es el eco de build"
                sh "mvn clean install"

            }
        }
        stage('Test'){
            steps{ 
            sh "mvn test"
        }
        }

        stage('Deploy'){
            steps{
            echo "simulando un despliegue simulado"
        }
        }

    }

    post{
        always{
            echo "Siempre se ewjecuta"

        }
        success{
              echo "exito"
        }

        failure{
              echo "fracazo"
        }
    }


}